CREATE TABLE IF NOT EXISTS users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          description VARCHAR(255),
                          created_at TIMESTAMP NOT NULL,
                          owner BIGINT NOT NULL,
                          CONSTRAINT fk_project_user FOREIGN KEY (owner) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(100) NOT NULL,
                       description VARCHAR(255),
                       status VARCHAR(50) NOT NULL,
                       priority VARCHAR(50) NOT NULL,
                       due_date DATE,
                       created_at TIMESTAMP NOT NULL,
                       project_id BIGINT NOT NULL,
                       assignee_id BIGINT,
                       CONSTRAINT fk_task_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
                       CONSTRAINT fk_task_user FOREIGN KEY (assignee_id) REFERENCES users(id)
);