spring.application.name=facilizationProject

# Setup database conenction
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:taskdb

# SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Autogenerate database schema by Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Enable h2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration